name: Whitesource Upload
on: [push]
jobs:
  whitesource:
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    steps:
    - name: "Clone Project"
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install requests library
      run: |
        python3 -m pip install requests
        python3 -m pip install pipenv==2018.11.26
    - name: Run whitesource
      env:
        WHITESOURCE_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
        WHITESOURCE_USER_KEY: ${{ secrets.WHITESOURCE_USER_KEY }}
      run: |
        # Replace environment variables
        ls -al
        cat wss-unified-agent.config.template
        envsubst < wss-unified-agent.config.template > wss-unified-agents.config
        bash <(curl -s -L https://raw.githubusercontent.com/whitesource/unified-agent-distribution/master/standAlone/wss_agent.sh ) -apiKey "$WHITESOURCE_API_KEY" -c "wss-unified-agents.config" -d .
        mkdir -p licenses
        python3 scripts/get_library_licenses_json.py > licenses/licenses.json
        curl -X "POST" "https://app.whitesourcesoftware.com/api/v1.3" -H 'Accept-Charset: UTF-8' -H 'Content-Type: application/json' -d $'{"productToken":"913e1446e73844588179f565f65fa3f19bd27c2facdf477ba1552574e44436e9","userKey": "'"$WHITESOURCE_USER_KEY"'","requestType": "getLicensesTextZip"}' --output licenses/licenses.zip
        curl -X "POST" "https://app.whitesourcesoftware.com/api/v1.3" -H 'Accept-Charset: UTF-8' -H 'Content-Type: application/json' -d $'{"productToken":"913e1446e73844588179f565f65fa3f19bd27c2facdf477ba1552574e44436e9","userKey": "'"$WHITESOURCE_USER_KEY"'","requestType": "getProductInventoryReport"}' --output licenses/licenses.xlsx
